# Generated by Django 5.2.12 on 2026-04-06 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('hearing', 'Hearing'), ('counseling', 'Counseling'), ('meeting', 'Meeting'), ('deadline', 'Deadline')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('participants', models.JSONField(default=list)),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('generated_by', models.CharField(max_length=100)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('format', models.CharField(default='PDF', max_length=10)),
                ('size', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Final', max_length=10)),
                ('summary', models.JSONField(default=dict)),
                ('downloads', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('suspension', 'Suspension'), ('counseling', 'Counseling')], max_length=20)),
                ('description', models.TextField()),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel')], default='PDF', max_length=10)),
                ('includes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Every Monday', 'Every Monday'), ('1st of Month', '1st of Month')], max_length=20)),
                ('time', models.TimeField()),
                ('recipients', models.JSONField(default=list)),
                ('format', models.CharField(default='PDF', max_length=10)),
                ('next_run', models.DateField()),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=5)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('address', models.TextField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(max_length=254)),
                ('attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conduct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='B', max_length=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Probation', 'Probation'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('clubs', models.JSONField(default=list)),
                ('achievements', models.JSONField(default=list)),
                ('warnings_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('actionable', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Behavioral', 'Behavioral'), ('Academic', 'Academic'), ('Social', 'Social')], max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=10)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('facilitator', models.CharField(max_length=100)),
                ('sessions', models.PositiveSmallIntegerField()),
                ('completed', models.PositiveSmallIntegerField(default=0)),
                ('success', models.CharField(blank=True, max_length=10, null=True)),
                ('students', models.ManyToManyField(related_name='intervention_programs', to='deputy_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('goals', models.JSONField(default=list)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('next_session', models.DateField()),
                ('status', models.CharField(default='On Track', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deputy_api.interventionprogram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_plans', to='deputy_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reported_by', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('Investigation', 'Investigation'), ('Pending Review', 'Pending Review'), ('Resolved', 'Resolved')], default='Investigation', max_length=20)),
                ('actions', models.JSONField(default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_cases', to='deputy_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Academic Guidance', 'Academic Guidance'), ('Personal Counseling', 'Personal Counseling'), ('Behavioral', 'Behavioral'), ('Group Counseling', 'Group Counseling')], max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Scheduled', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='deputy_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('In-School', 'In-School'), ('Out-of-School', 'Out-of-School')], max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=10)),
                ('assigned_by', models.CharField(max_length=100)),
                ('parent_notified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='deputy_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.JSONField(default=dict)),
                ('notifications', models.JSONField(default=dict)),
                ('preferences', models.JSONField(default=dict)),
                ('security', models.JSONField(default=dict)),
                ('discipline_settings', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
